# Site settings
title: Title Coming Soon
header-img: img/home-bg.png
email: aryedov.e@gmail.com
copyright_name: arye-dov-eidelman
description: > # this means to ignore newlines until "baseurl:"
  Subtitle Coming Soon
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  arye-dov-eidelman
learn_profile: arye-dov-eidelman
email_username: aryedov.e@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
